### PR TITLE
Added missing safe-buffer dependency

### PR DESCRIPTION
**Pull request by michaelhigham**

### CODE REVIEW

**Review by PabloB94 — APPROVED** [review]
LGTM, but we should see if there's a replacement for this as well since it's not being maintained

**Comment by michaelhigham** [comment]
Thanks Pablo. Unfortunately the only alternative I could find was porting the code to the new API:
[Porting to the Buffer.from() / Buffer.alloc() API](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/)

**Comment by PabloB94** [comment]
Feel free to create a task to do that migration and assign it to me. This may be happening in more of our Node.js projects, we should check

**Comment by michaelhigham** [comment]
OK sure, I will create a task for this.

**Pull request merged**
